### ISSUE TITLE
Add some 101 information to the ID Check view

### ISSUE THREAD

**Issue by codersquid** [hef/ps1auth#129]
We had a member who said they did not know
* authorization is required for using tools
* about the wiki
* about the mailing list
* or the membership agreement

The welcome mail has some of this information but email delivery is not reliable.

We should remind board members to share information by showing a list on the page.

**Comment by codersquid** [comment]
A user friendly wait to allow this information to show up is to use something django-flatblocks. You'd add a flatblock to the template, and then users with the right pemissions can edit that part of the page as though it were a wiki.

**Comment by codersquid** [comment]
django-flatblocks has some unicode error when you try to install it in python 3.5. Would you consider switching to python 3.x stable branch?

I'll ask @funkybob maybe about 3.5 before opening any issue over there. maybe it's just a user mistake.

```
$ pip install django-flatblocks
Collecting django-flatblocks
  Using cached django-flatblocks-0.9.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-noaejp12/django-flatblocks/setup.py", line 10, in <module>
        long_description=open('README.rst').read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6692: ordinal not in range(128)
```

**Comment by funkybob** [comment]
I just tested on py3.5 locally and it works... though I do recall seeing this error before.

Can you test against mater?

**Comment by hef** [comment]
as far as Ican tell, python 3.5 is the stable branch

That doesn't look like a python 3.x  error, that looks like the 'README.rst' is not ascii (likely utf8) and it's trying to read it as ascii.

**Comment by hef** [comment]
pinging @funkybob, this one got me curious, so I Iooked into it.
It looks like open() by default will use  locale.getpreferredencoding(False), meaning the default encoding that python reads a file with is dependent on the system configuration.  I'd recommend just setting the encoding to 'utf8' in the call to open() and not seeing this bug in the future.

@codersquid I'm guessing your dev machine's locale is set to 'C' or something similar.  You might have more luck if you switch it to en_US.UTF-8 or similar.

**Comment by codersquid** [comment]
@funkybob I did try it against master and saw the same error. I haven't tried following hef's suggestion yet.

@hef I'm wondering if there is something different in how 3.5 handles encodings vs. 3.4 because I didn't get the error when trying this with a virtual env using python 3.4. I haven't tried your suggestion yet.

@hef re stable, from the [docs labels](https://docs.python.org/3.4/) 3.5 is dev. I'm opinionated about using stable things vs. dev things; but you are the BFDL and it's your prerogative.

**Comment by asl2** [comment]
@codersquid  https://www.python.org/downloads/release/python-350/ says 3.5 is released.

**Comment by codersquid** [comment]
:+1:  @asl2

**Comment by funkybob** [comment]
The line raising the error was inherited... can someone see if changing to this fixes it, please?

    long_description=open('README.rst').read().decode('utf-8'),

**Comment by codersquid** [comment]
@funkybob hi, it fixes it.

**Comment by codersquid** [comment]
@funkybob no, sorry. It still doesn't work. (good morning, I am groggy and I made a 3.4 virtualenv to test it, d'oh)

**Comment by codersquid** [comment]
@hef the locale is whatever vagrant set up on the arch vm.

**Comment by hef** [comment]
Does changing the line to 

        long_description=open('README.rst',encoding='utf-8').read()

work?

**Comment by codersquid** [comment]
@hef yep, thanks!

**Comment by funkybob** [comment]
I just pushed a change to use io.open so it will still work in py2.7...

**Comment by codersquid** [comment]
@funkybob thanks, please do.
