### ISSUE TITLE
vagrant up has an ImportError

### ISSUE THREAD

**Issue by codersquid** [hef/ps1auth#134]
Is this happening to anyone else?

```
==> default: Successfully installed Django-1.8.2 Pillow-2.6.0 amqp-1.4.6 anyjson-0.3.3 argparse-1.4.0 beautifulsoup4-4.3.2 billiard-3.3.0.19 celery-3.1.17 coverage-3.7.1 dateutils-0.6.6 django-bootstrap3-5.0.3 django-bootstrap3-datetimepicker-2.2.3 django-celery-3.1.16 django-ckeditor-4.4.6 django-debug-toolbar-1.2.2 django-jenkins-0.17.0 django-model-utils-2.2 django-reversion-1.8.7 django-tables2-1.0.0.dev0 docutils-0.12 html2text-2014.12.5 kombu-3.0.24 ldap3-0.9.8.4 psycopg2-2.5.1 pyasn1-0.1.9 python-dateutil-2.4.2 pytz-2013b0 redis-2.10.3 six-1.10.0 sqlparse-0.1.16
==> default: Collecting gunicorn
==> default:   Downloading gunicorn-19.3.0-py2.py3-none-any.whl (110kB)
==> default: Installing collected packages: gunicorn
==> default: Successfully installed gunicorn-19.3.0
==> default: /home/vagrant/venv/lib/python3.5/site-packages/django_jenkins/tasks/with_coverage.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
==> default:   from django.utils.importlib import import_module
==> default: /home/vagrant/venv/lib/python3.5/site-packages/ckeditor/widgets.py:10: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
==> default:   from django.forms.util import flatatt
==> default: Traceback (most recent call last):
==> default:   File "/vagrant/manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 312, in execute
==> default:     django.setup()
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
==> default:     apps.populate(settings.INSTALLED_APPS)
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
==> default:     app_config.import_models(all_models)
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
==> default:     self.models_module = import_module(models_module_name)
==> default:   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
==> default:     return _bootstrap._gcd_import(name[level:], package, level)
==> default:   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
==> default:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
==> default:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
==> default:   File "<frozen importlib._bootstrap_external>", line 662, in exec_module
==> default:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
==> default:   File "/vagrant/zoho_integration/models.py", line 5, in <module>
==> default:     from member_management.models import Person
==> default:   File "/vagrant/member_management/models.py", line 18, in <module>
==> default:     from bs4 import BeautifulSoup
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/bs4/__init__.py", line 30, in <module>
==> default:     from .builder import builder_registry, ParserRejectedMarkup
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/bs4/builder/__init__.py", line 308, in <module>
==> default:     from . import _htmlparser
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/bs4/builder/_htmlparser.py", line 7, in <module>
==> default:     from html.parser import (
==> default: ImportError: cannot import name 'HTMLParseError'
==> default: /home/vagrant/venv/lib/python3.5/site-packages/django_jenkins/tasks/with_coverage.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
==> default:   from django.utils.importlib import import_module
==> default: /home/vagrant/venv/lib/python3.5/site-packages/ckeditor/widgets.py:10: RemovedInDjango19Warning: The django.forms.util module has been renamed. Use django.forms.utils instead.
==> default:   from django.forms.util import flatatt
==> default: Traceback (most recent call last):
==> default:   File "/vagrant/manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 312, in execute
==> default:     django.setup()
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/django/__init__.py", line 18, in setup
==> default:     apps.populate(settings.INSTALLED_APPS)
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
==> default:     app_config.import_models(all_models)
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
==> default:     self.models_module = import_module(models_module_name)
==> default:   File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
==> default:     return _bootstrap._gcd_import(name[level:], package, level)
==> default:   File "<frozen importlib._bootstrap>", line 986, in _gcd_import
==> default:   File "<frozen importlib._bootstrap>", line 969, in _find_and_load
==> default:   File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
==> default:   File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
==> default:   File "<frozen importlib._bootstrap_external>", line 662, in exec_module
==> default:   File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
==> default:   File "/vagrant/zoho_integration/models.py", line 5, in <module>
==> default:     from member_management.models import Person
==> default:   File "/vagrant/member_management/models.py", line 18, in <module>
==> default:     from bs4 import BeautifulSoup
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/bs4/__init__.py", line 30, in <module>
==> default:     from .builder import builder_registry, ParserRejectedMarkup
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/bs4/builder/__init__.py", line 308, in <module>
==> default:     from . import _htmlparser
==> default:   File "/home/vagrant/venv/lib/python3.5/site-packages/bs4/builder/_htmlparser.py", line 7, in <module>
==> default:     from html.parser import (
==> default: ImportError: cannot import name 'HTMLParseError'
==> default: Created symlink from /etc/systemd/system/sockets.target.wants/ps1auth.socket to /etc/systemd/system/ps1auth.socket.
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/nginx.service to /usr/lib/systemd/system/nginx.service.
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/redis.service to /usr/lib/systemd/system/redis.service.
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/celery.service to /etc/systemd/system/celery.service.
==> default: Created symlink from /etc/systemd/system/sockets.target.wants/systemd-journal-gatewayd.socket to /usr/lib/systemd/system/systemd-journal-gatewayd.socket.

```

**Comment by hef** [comment]
update your venv from the requirements.txt file
